### PR TITLE
add facebook and instagram links

### PR DESCRIPTION
**Pull request by jaredcunha-usds**
One question… should we update the script to include Instagram and Medium domains? https://github.com/usds/website/blob/master/js/script.js#L140

screen shot 2018-08-29 at 3 41 28 pm

### CODE REVIEW

**Comment by nacingov** [comment]
> should we update the script to include Instagram and Medium domains? 

Yes.

**Review by nacingov — DISMISSED** [review]

**Comment by jaredcunha-usds** [comment]
@nacingov any preference if we do it with this PR or a new one?

**Comment by nacingov** [comment]
I’d push more commits here, personally.

**Comment by KelseyHastings** [comment]
@nacin how long does it take for this to show up on the current site?

**Review by KelseyHastings — DISMISSED** [review]

**Comment by jaredcunha-usds** [comment]
@nacin Okay - pushed a commit to prevent the 'outgoing' modal from appearing on Medium and Instagram domains.

**Review by nacingov — APPROVED** [review]

**Pull request merged**
