### PR TITLE
add data science as a role in How we work

### PR DESCRIPTION
**Pull request by lisac-usds**
## summary of changes
- adds a section for Data Science on the [How we work](https://www.usds.gov/how-we-work) page 
- updates a sentence on the [Apply](https://www.usds.gov/apply) page about skills we hire for
- backend: minor refactoring to use a `for` loop

### CODE REVIEW

**Comment by lisac-usds** [comment]
screenshots:

- How we work:
 

- Apply:

**Comment by bernars-usa** [comment]
It looks fantastic!

**Comment by LauraUSDS** [comment]
Looks mostly good! A few tiny tweaks:

- “S” in “science” in title should be lowercase (for consistency w/ others; titles on this page use sentence case, not title case)
- We’ll need to re-order the CoP descriptions so that the backgrounds of the illustrations alternate navy + bright blue. Recommend: eng, design, data sci, prod, procur. (current order is: design, eng, prod, procur…alphabetical but gone slightly wrong w/ the addition of procurement last summer (likely bc of the illustration bg color!))
- while we’re at it…can we change the “and” at the end of the “skills you might bring to the eng community” blurb to an “or” (to be consistent across all CoP descriptions)

**Comment by anggrossfeld** [comment]
I agree with @LauraUSDS tweaks but other wise looks fab, and bravo on the quick turnaround! @lisac-usds @LisaHwang @LauraUSDS

**Comment by LisaHwang** [comment]
Looks good! Going to do a final confirmation w/Jordan tomorrow 8/19, will follow up.

**Comment by lisac-usds** [comment]
Screenshot of the top portion of the How we work page after the latest round of fixes:

**Review by LauraUSDS — COMMENTED** [review]
looks good to me - as long as you're cool with using "developer" instead of "engineering" on the apply page (as the Eng CoP director). I also pushed a new commit that tweaked the into blurb on how-we-work so that we arent listing out 7 positions - pls check I did it correctly! otherwise, good to go on my end

**Comment by LisaHwang** [comment]
- Thumbs up from talent/Jordan on the data science blurb, we are good to go. P.S he will be making the announcemenat this coming staff meeting on 8/24
- "Data Science" has been added to "What is your primary area of expertise?" as its own value on the USDS.gov/apply page.
- Data Science resume review queue (all/pending) has been created as well
- Side note: Title case and sentence case don't match with what's on the website. Probably need to update salesforce?

image

**Pull request merged**
