### PR TITLE
add a note explaining mollie

### PR DESCRIPTION
**Pull request by wslack**
Someone tweeted confusion; might be worth a note of explanation?

https://twitter.com/Ltrademark/status/1103019177336553473

### CODE REVIEW

**Comment by jaredcunha-usds** [comment]
LOL!

**Comment by ButtersUSDS** [comment]
Looks great to me!

**Review by ButtersUSDS — APPROVED** [review]

**Comment by wslack** [comment]
🎉

**Comment by ButtersUSDS** [comment]
That was an awesome tweet. Good catch.

**Pull request merged**
