### PR TITLE
Add USDS's July 2017 Report to Congress to the website

### PR DESCRIPTION
**Pull request by nacingov**
Transmitted to the Hill on Monday; public comms start Tuesday.

It would be great if someone could review all of the pages for any issues, as well as opportunities to hyperlink or reference other published things.

I made a bunch of internal tweaks to improve how we use the Jekyll collection that holds all of these, now that we actually have a second report. The website should now be much easier to update for any subsequent reports.

### CODE REVIEW

**Comment by nacingov** [comment]
As it's late, I'm bypassing our review requirement to merge this.

**Comment by nacingov** [comment]
@stephaniefaith @amiklik @sarahsaltiel This is live on usds.gov and everything looks good. Please review the pages for any issues, as well as opportunities to hyperlink or reference other published things. Thanks! 🎉

**Comment by sarahsaltiel** [comment]
You're my hero. Thank you!!!

**Comment by sarahsaltiel** [comment]
@nacin when posting the link, it populates Matt's Signature as a picture. Can we have the link point to the Capitol Hill sketch?

**Pull request merged**
