### PR TITLE
update d&i brochure

### PR DESCRIPTION
**Pull request by melissajschaff**

### CODE REVIEW

**Review by LauraUSDS — APPROVED** [review]

**Comment by melissajschaff** [comment]
USDS_1Sheet_DI_Feb2019.pdf should be removed/replaced by the new file

**Comment by jaredcunha-usds** [comment]
@melissajschaff @LauraUSDS Do either of you have strong thoughts about just overwriting the file with a new one? You wouldn't have to do multiple updates this way, but the tradeoff is that you lose having super clear past versions; GitHub have version control, but you have dig a little deeper to get those past versions.

**Comment by LauraUSDS** [comment]
@jaredcunha I track the different versions (+ design files of this) elsewhere in GH, so I don't mind overwriting the file. It's a little harder to know which one it is then, but I figure we can always look at the upload date and/or the date marker in the actual PDF. We should change the file name this time tho, since it currently includes "Feb2019" as part of the filename, which could get confusing down the line. Make sense?

@melissajschaff

**Comment by jaredcunha-usds** [comment]
All good, just wanted to flag that. I'll let @melissajschaff reply, and then I'll merge this in along with the corresponding link PR.

**Comment by melissajschaff** [comment]
@jaredcunha @LauraUSDS I defer to Laura, but I think having one file that lives in the website repo is fine, even if it is overwritten. Now that I understand jekyll a smidge, I think it makes more sense to only have the most current file in this repo and have the other docs live historically in the design repo or another repo for access, as necessary. Especially since the file name in assets has the date affiliated with it

**Comment by LauraUSDS** [comment]
Let it be so! @jaredcunha here's the latest D&I one-sheet (w/ a generic name that we can just overwrite a couple times a year). I think you're all set to resolve this now, but lmk otherwise. let's continue the discussion re permissions in Slack...
[USDS_1sheet_D&I.pdf](https://github.com/usds/website/files/3837345/USDS_1sheet_D.I.pdf)

**Comment by jaredcunha-usds** [comment]
Okay sounds good. I'll go ahead and update the file and config, as well as close these two PRs. 

BTW - you all are tagging my personal GitHub account!

**Comment by LauraUSDS** [comment]
@jaredcunha-usds Bah! How is it even suggesting that one?! Sorry about that...

**Comment by jaredcunha-usds** [comment]
closing because this was updated here: https://github.com/usds/website/pull/480

**Pull request closed without merging**
