### PR TITLE
Build system css fix

### PR DESCRIPTION
**Pull request by TomNUSDS**
- css:sass:watch seemed wrong. Fixed it.
- Add comment to /assets/stylesheets/application.css
- Move a person md at root into _draft-people/

### CODE REVIEW

**Review by drew-usds — DISMISSED** [review]
LGTM!

**Comment by drew-usds** [comment]
@TomNUSDS OMG finally got this working locally sorry this took so long. In the end: I had to kill all my terminal windows/processes, delete the `_site` directory, and reboot to get it building correctly. Just ran a bunch of tests editing sass and it's working!

There were a couple moments on my localhost where the live reload didn't totally work and I had to do a hard refresh to see a sass change actually take effect. I wasn't able to consistently replicate so maybe was just the live reload getting ahead of Jekyll compiling stuff? It's still compiling correctly though.

**Comment by TomNUSDS** [comment]
@drew-usds I think I fixed it so the /styles.css isn't in github anymore.

**Comment by TomNUSDS** [comment]
@drew-usds 
As far as a slow home page goes, these two carousel image files are really big:
- images/project-ssa-card.jpg (2MB)
- images/project-cdc-simple-report-card.jpg (3.9MB)

**Review by drew-usds — DISMISSED** [review]
LGTM!

**Comment by drew-usds** [comment]
> As far as a slow home page goes, these two carousel image files are really big:
> * images/project-ssa-card.jpg (2MB)
> * images/project-cdc-simple-report-card.jpg (3.9MB)

@TomNUSDS I can res those down if you want to include that in this PR? Or we could do a separate one with a pass on all the imgs?

**Comment by TomNUSDS** [comment]
Can you down sample if you have time? My other projects are a bit crazy for another week.

I'm also worried I might edit an image that's used by the carousel and main article page.

**Comment by drew-usds** [comment]
@TomNUSDS just added two new commits:

1. Scales down the images you flagged
2. Tried commenting out the default [Jekyll settings](https://github.com/jekyll/jekyll-sass-converter#usage) for sass. The local server and build scripts in package.json are still working fine for me and not generating the additional `styles.css` file. I am not _totally_ sure how this will behave on the GH Pages branch, however. We should test this on staging first.

**Review by drew-usds — APPROVED** [review]
👍

**Pull request merged**
