### PR TITLE
[Privacy] Anonymize IP address in Google Analytics

### PR DESCRIPTION
**Pull request by robalexdev**
This change will request that Google mask the last octet of the IP address in memory before performing further processing.
https://support.google.com/analytics/answer/2763052?hl=en

### CODE REVIEW

**Comment by robalexdev** [comment]
Without this change, I do not believe the following statement in the privacy policy is true.

https://www.usds.gov/privacy

> We have also limited the provider’s ability to see your full IP address (a process known as “IP masking”).

**Comment by jaredcunha-usds** [comment]
@RobertAlexanderUSDS - We recently updated the site, and with it, I was given a different snippet than what we're currently using. Any chance you can take a look at that and let me if this PR is still relevant, and if so, how to address? https://github.com/usds/website/blob/master/_layouts/default.html#L117

**Comment by robalexdev** [comment]
I think this is still relevant, I'm seeing a call to google analytics, but it doesn't have the aip parameter that controls this.
I'm guessing this is because we don't anonymize IPs when we setup google tag manager.
I can try to update this for that.

**Comment by robalexdev** [comment]
I've moved this to a new PR:
https://github.com/usds/website/pull/411

**Pull request closed without merging**
