### PR TITLE
make copy edits to SBA project

### LINKED ISSUE #122: Copy edit request from SBA
Hey team - Aditi Dussault, a senior advisor at SBA and certify.sba.gov guru, has asked for a copy change on the USDS site where it describes the SBA project. The blurb says:

"For small business owners, navigating the contractor certification process is burdensome, involving hours of paperwork and manually scanning dozens of documents. We assisted the Small Business Administration (SBA) in establishing an agile procurement to modernize technology and streamline the certification process. The newly launched certify.SBA.gov saves small businesses time and money, and it increases the SBA’s capacity to provide small businesses access to _the_ federal contracting space **and capital**."

The '**and capital**' portion is not an accurate representation of the project goals at this time. Can it be removed? I added the '_the_' because it sounds awkward without it, to me. 

cc: @mindware

### PR DESCRIPTION
**Pull request by cew821**
This fixes #122

It changes this: "...it increases the SBA's capacity to provide small businesses access to federal contracting space and capital."

to this: "... and it increases the SBA's capacity to provide small businesses access to **the federal contracting space.**"

### CODE REVIEW

**Comment by cew821** [comment]
As per @davidrkaufman, this is OK to merge. For now we'll keep it so @chrisfrommann does all merges to master and gh-pages, at least until we discuss a standard way to do edits across a larger number of people.

**Comment by cew821** [comment]
@chrisfrommann this one is simple to merge, it'd be great to get it fixed soon since SBA leadership requested it.

**Comment by davidrkaufman** [comment]
@chrisfrommann – bumping this

**Comment by cew821** [comment]
I just merged this since it was approved by comms and non-controversial, and also causing a small issue with an agency partner. Let's create a documented process for merging changes to master / gh-pages going forward.

**Pull request merged**
