### PR TITLE
[WIP] Site fixes

### PR DESCRIPTION
**Pull request by dmethvin-gov**
Hey @jaredcunha-usds when you get a chance let's talk about these changes.

I had questions about whether the artifacts should be committed to the repo. Right now several of them are not and I added them in some commits, but I'm not sure that's the way to go.

Setting a reminder to myself to improve the README, I just now remembered it. I think I got all the missing dependencies.

The big remaining performance issue is with the uswds.css file, it's 800KB 🐌 . Can that be cut down, or at the very least can we use the minified version? 

BTW I just saw that USWDS 2.0 is on the verge of release, it sounds like there may be some breaking changes--oh joy!

### CODE REVIEW

**Comment by jaredcunha-usds** [comment]
Couple things: 

The site doesn't actually link to the USWDS.css. It imports it [here](https://github.com/usds/website/blob/master/assets/stylesheets/application.scss#L4) and Jekyll minifies it. You can the [css file used in production](https://www.usds.gov/assets/stylesheets/application.css). 

I have PR set for updating USWDS2.0. [This PR](https://github.com/usds/website/pull/421/files) fixed a lot of breaking things between the alpha build and beta5, however, they are up to 7 now and there's a ton of breaking changings there that I'll need to address. I think I'll stick to managing USWDS in that branch, because even getting to beta5 was huge chore.

I'm not sure we need those assets. Were they 404ing?

For all those packages, I think A LOT of them can be cleaned out, but I've made some big changes to the way I'm using gulp in that other PR.

Out of curiousity, is it possible to break up some of this work into separate PR's? It'll make it a lot easier for me to work these fixes in while keeping on top of that big pending USWDS update.

**Comment by dmethvin-gov** [comment]
> The site doesn't actually link to the USWDS.css. It imports it here and Jekyll minifies it. You can the css file used in production.

The first line of the `application.css` file is `@import uswds.css` and that doesn't get minified. It's served directly because it's a `.css` file. You can see all 800KB being sent in the network tab in devtools. You could maybe pull in the `.scss` parts from USWDS? That way you could also exclude some of the things we don't need like form styles.

> I'm not sure we need those assets. Were they 404ing?

The build process copies them, maybe it shouldn't be doing that but the files end up in the `assets` directory.

> For all those packages, I think A LOT of them can be cleaned out, but I've made some big changes to the way I'm using gulp in that other PR.

All I know is that when I try to run a build it needed all of them or it couldn't continue. Even at that, it died before it completed. The first thing the build does it try to clean out the assets it copies, so I had to `git reset` to get back the assets committed in the repo in order to do the fixes in this PR.

Once you get things to where you think they should be, I highly recommend cloning that into a new directory on your system and trying to build according to the README directions. That will let you know if you have all the `package.json` and build process right.

> Out of curiousity, is it possible to break up some of this work into separate PR's? It'll make it a lot easier for me to work these fixes in while keeping on top of that big pending USWDS update.

The main changes here are the lazy-loaded images, which required a change to the way the carousel card heights were calculated.  The Instagram feed is also lazy now too. The other things probably conflict with the build changes you're making. I'll be glad to just redo those on top of whatever you end up with, or I can break those out into a different PR if you want to merge them sooner.

**Comment by jaredcunha-usds** [comment]
Gah! You're right. Totally missed that. I'm looking to update this in my other PR anyway, but perhaps in the meantime, convert it to .scss so it minifies with the Jekyll build? 

Were you using `npm build` or `gulp build`? I'm not actually using those to build to the site. It's all using the main Jekyll build.

**Comment by jaredcunha-usds** [comment]
The `package.json` is really out of date.

**Comment by dmethvin-gov** [comment]
> perhaps in the meantime, convert it to .scss so it minifies with the Jekyll build?

What do you think the timeline is on getting those cleanups done? If it's going to be more than a week I can put together a simpler set of changes for a PR. It would be helpful if you pushed your WIP into a branch so I can look at it and be sure we aren't going to be conflicting.

> Were you using npm build or gulp build? I'm not actually using those to build to the site. It's all using the main Jekyll build.

Ah, ok. That makes sense, I noticed that Jekyll was set up to watch some of the `node_modules` directories for changes, maybe it's moving some of those to `assets`? If so we should remove the parts of those directories being committed and `.npmignore` them.

It would be a good idea to remove anything not being used in the gulp setup. There's already an `npm start` that runs Jekyll which is good.

**Comment by dmethvin-gov** [comment]
@jaredcunha-usds as a quick test I renamed `uswds.css` to `uswds.scss` but it only gets the bundle down to about 650KB which is still super big for a site as simple as this one. Hopefully we can filter out some of the stuff we aren't using.

**Comment by jaredcunha-usds** [comment]
@dmethvin-gov I think I'll change it to a .scss file. The USWDS mentioned in the TTS Slack that they'll have a final version of 2.0 out in about two weeks.

The new branch that I'm working on can address some of the issues because it uses USWDS's theming capabilities. I just have some questions about what that might mean for the build process and if that means putting built files under version control.

**Comment by jaredcunha-usds** [comment]
By the way, this is WIP branch: https://github.com/usds/website/tree/uswds-update

This Beta 5. Beta 6 introduced a TON of breaking changes that I have to incorporate.

**Comment by jaredcunha-usds** [comment]
I've added a cherry-picked PR of your work: https://github.com/usds/website/pull/430

This brings in most of the optimizations but leaves out some of the package.json and asset additions that might not play nice the USWDS update.

**Comment by jaredcunha-usds** [comment]
Most of these added in #430. Closing.

**Pull request closed without merging**
