### PR TITLE
link to 'How we work' from the Apply page

### PR DESCRIPTION
**Pull request by lisac-usds**
## summary of changes
To encourage folks to review the competencies before applying, add a link to [How We Work](https://www.usds.gov/how-we-work) from the [Apply](https://www.usds.gov/apply) page.

### CODE REVIEW

**Comment by lisac-usds** [comment]
hi @bernars-usa , could you recommend an implementation?

one approach (implemented in 5ddd2b5): add a button to the top section of the [Apply](https://www.usds.gov/apply) page. preview:
Screen Shot 2021-03-17 at 18 04 39

**Comment by bernars-usa** [comment]
I don't think a button has enough explanation for this purpose. Instead, an inline link near the top might be better:

Screen Shot 2021-03-18 at 12 08 46 PM

**Comment by lisac-usds** [comment]
Thank you, @bernars-usa ! Implemented https://github.com/usds/website/pull/619#issuecomment-802054258 in 7f8384c.

preview:

**Review by bernars-usa — APPROVED** [review]

**Comment by bernars-usa** [comment]
Thanks so much for your help, @lisac-usds! ❤️

**Pull request merged**
