### PR TITLE
Blog updates

### PR DESCRIPTION
**Pull request by cew821**
This PR creates a new blog summary for the "Values" post published Monday. It also adds a section to the readme describing how to add new blog summaries.

### CODE REVIEW

**Comment by cew821** [comment]
@davidrkaufman I updated the blog page with a link to our latest post. Check out the image and the lede I wrote to make sure it is OK:

image

Once @davidrkaufman approves, we can merge to `gh-pages`

**Comment by davidrkaufman** [comment]
@cew821 LGTM! thanks

**Comment by cew821** [comment]
@chrisfrommann This is in your court now. Would be great to get up soon as the post went out already.

**Comment by chrisfrommann** [comment]
Donezo!

**Pull request merged**
