### PR TITLE
Add new blog article

### PR DESCRIPTION
**Pull request by amwhitty**

### CODE REVIEW

**Comment by amwhitty** [comment]
@lisac-usds I made 2 small edits to the website but am having trouble previewing them before I merge. I get an error when trying to view using Netlify.  Any chance I can trouble you to take a quick look?

**Comment by lisac-usds** [comment]
@amwhitty the changes you've prepared look good to me. i'm not sure why the errors are coming up, but i do see what you mean. i'll take a look today, should have this ironed out by tomorrow morning.

**Comment by lisac-usds** [comment]
@amwhitty : this is deployed on the preview environment! 

Why this wasn't working before: I suspect a configuration change slipped in. Via 792adb3 I adjusted those to be in sync with what's currently on the live site. For the record, this is not a bug you introduced; and I'm sorry it got in your way. 

For convenience, here are screencaps of the areas you updated:
,   ,

**Review by lisac-usds — APPROVED** [review]

**Comment by amwhitty** [comment]
@lisac-usds Thank you! The screenshot previews look good. Should I go ahead and merge to main?

**Comment by lisac-usds** [comment]
@amwhitty go for it!

**Pull request merged**
