### PR TITLE
Mobile navigation updates

### PR DESCRIPTION
**Pull request by chrisfrommann**
- Updated UI for mobile navigation and added mission, values, and story
- Added html5shiv.js so that MSIE < 9 doesn't look like complete crap

screen shot 2016-10-13 at 21 23 15

### CODE REVIEW

**Comment by alohaj9** [comment]
@chrisfrommann @davidrkaufman 

On mobile, "About" now only has 1) Mission 2) Focus Areas

We are missing Values and Our Story.

**Comment by davidrkaufman** [comment]
Known issue, but Chris, can you provide a timing update for fix?

Sent from my iPhone

On Oct 19, 2016, at 8:12 AM, Janine Gianfredi <notifications@github.com<mailto:notifications@github.com>> wrote:

@chrisfrommannhttps://github.com/chrisfrommann @davidrkaufmanhttps://github.com/davidrkaufman

On mobile, "About" now only has 1) Mission 2) Focus Areas

We are missing Values and Our Story.

##

**Comment by chrisfrommann** [comment]
Hi @alohaj9, @davidrkaufman, this was fixed in this PR, but never pushed to prod; it's live now!

**Comment by alohaj9** [comment]
Looks great. Thank you @chrisfrommann @davidrkaufman !

**Pull request merged**
