### PR TITLE
Change salary cap

### PR DESCRIPTION
**Pull request by LauraUSDS**
update salary cap listed on /apply page to 2022 level

### CODE REVIEW

**Comment by LauraUSDS** [comment]
@lisac-usds I swear GH is conspiring against me today....

I am literally just trying to change the salary cap (aka, just ONE number) on the apply page. Somehow, GH has also: brought over changes from another branch that I'm not ready to send to staging yet (the two vaccines.gov ones), and has also brought over changes that are already made + live on the site (the first two listed above). 

My thinking was that we could publish the salary cap edit to staging, and then that could get pushed live with the (one million) other edits we are still making, once those are done. 

Could you help me sort this out whenever you have a minute in the next 2 weeks? No rush, truly.

**Comment by lisac-usds** [comment]
@LauraUSDS I see what you mean about the extra files that are being pulled in... gah. 

What I'd recommend is removing those vaccines.gov changes from this branch. That'll keep this particular PR scoped to the salary cap change. Also, those changes exist in another active branch - it's not like we'd be losing the changes, more of just controlling at what stage they get added in. 

I'll do that shortly, and from there I'll leave it to you to decide when to merge in this PR.

**Review by lisac-usds — APPROVED** [review]

**Comment by LauraUSDS** [comment]
Thank you @lisac-usds ! As always, you are the best. Thank you for always saving the day :) 

So I know for next time (this has happened before....), is the way you "remove" the unwanted changes (aka, the vaccines ones in this case) simply by deleting that markdown file (on this branch)?

**Comment by lisac-usds** [comment]
Yep, deleting the file on the branch, that's exactly what I did in this case. 
Until next time, GH! :)

**Pull request merged**
