### PR TITLE
Auto deploy to GH Pages with workflow Action

### PR DESCRIPTION
**Pull request by SteveMattinglyUSDS**
#777 These workflow actions were first implemented to auto deploy to GH Pages on a push to master. That code is still present, but commented out to try a different approach: auto deploy on a Release publication.

We need to decide which approach to use, and clean up code accordingly before thinking about merging. From a strictly technical perspective, I recommend the Release publication approach. It is much cleaner and airtight. It does add an extra step from a user perspective, but it is a step that might be seen as useful.

Regardless, there are two config changes needed if we merge some version of this to master: 

- [ ] remove the branch protection rule that allows GH Pages deploys from master only; these Actions allow for rollback/deploy of arbitrary commits, but this rule prevents such
- [ ] create a repo var `MOCK_PAGES_DEPLOY=FALSE`. Until the var exists, the Actions will perform all steps *except* for actually copying the build results to the Pages area. This is an extra failsafe against the implications of a repo having only one Pages "space".

### CODE REVIEW

**Comment by kategreenUSDS** [comment]
Agree on the `release` method making more sense. 

We'll need to document the new process as part of wrapping this up. We'll also want to show it to Alison

**Comment by SteveMattinglyUSDS** [comment]
I have created documentation in the wiki: https://github.com/usds/website/wiki/Publishing-a-Release-to-usds.gov

Everything is converted to trigger by Release publication. I am converting this to full PR status, ready for review. When we are ready, it can be merged into master and tested in the real repo. Until we set a new env var, it won't actually touch usds.gov, only go through all the motions and save the build as an Actions artifact.

**Comment by rachellanman** [comment]
Not sure I understand the approach to changing the config file in the GH action, since jekyll has an override feature for the build built into the command line. "[Specify config files instead of using _config.yml automatically. Settings in later files override settings in earlier files.](https://jekyllrb.com/docs/configuration/options/)"
```
echo "${{ github.repository }}" > /tmp/repo; grep ^usds/website$ /tmp/repo && echo "" > /tmp/baseurl
          echo BASEURL=`cat /tmp/baseurl` >> $GITHUB_ENV 

'echo >> _config.yml && echo "domain: \"https://usds.gov\"" >> _config.yml && cat _config.yml'

bundle exec jekyll build --config _config.yml --baseurl "${{ env.BASEURL }}"
```

when you could create a `_config_prod.yml` which contains the 3 keys that are different:
```
_config_prod.yml 
domain: "https://usds.gov"
baseurl: "" 
repository: "usds/website"
```
then the build command looks like this:
`
bundle exec jekyll build --config _config.yml _config_prod.yml`

Or even simpler, don't change the `_config` - it's basically prod by default,  and I can build a GH action in `staging-website` which overrides those 3 values.

**Comment by SteveMattinglyUSDS** [comment]
@rachellanman This supports more than staging and prod. Since I'm working on the process for deploying, and I have to use a repo's one/only Pages "space", and it has to be (eventually) done from the `master` branch, I have set it up so that it works in forks of the prod repo, too. That way I can test and debug (most of) the deploy process without being in the prod repo.

First and third statements you quoted: I'm using the Jekyll command line to set the build baseurl. It's taken from an env var that is in turn taken from a tmp file. The file is written to contain the repo name. If the contents are `usds/website` then the file is overwritten to be blank. So, baseurl is empty string for prod, repo name for any other.

Second statement you quoted runs when repo is `usds/website`. It appends to (the runner's temporary working copy of) `_config.yml`. First, a blank line in case the file has no line break at the end. Then, `domain: "https://usds.gov"`. The `cat` bit at the end was for debugging and should be removed. This gets the needed var to the prod build (it's custom, so I don't think it can be set on the command line). The `domain` var is only used in `_head.html` to set absolute urls for some meta tags and such. So non-prod sites get along without `domain` without any real problem.

**Comment by rachellanman** [comment]
one other thought - I would recommend squash merging this, so all the commits in this PR don't clutter the commit history of the repo

**Comment by SteveMattinglyUSDS** [comment]
Absolutely. I can't run Actions locally, so every change is commit, push, create Release ... Anticipating squash, I kinda gave up on some commit messages.

**Comment by SteveMattinglyUSDS** [comment]
I think the Action is much cleaner now. It treats `_config.yml` as for prod, and other repos simply change baseurl on the build command line. They can accept custom `domain="https://usds.gov"` without breaking because that is only used for meta tags that arguably should point to usds.gov anyway-- even on other builds. In other words, we now have the same effect as if the things using `domain` var were hardcoded to usds.gov.

**Review by rachellanman — DISMISSED** [review]

**Review by rachellanman — APPROVED** [review]

**Pull request merged**
