### PR TITLE
update footer

### PR DESCRIPTION
**Pull request by lisac-usds**
## summary of changes
Adds to the footer a link to the USDS Discovery Sprint Guide. 

cc @K-Jurick @kathypham-gov

### CODE REVIEW

**Comment by LauraUSDS** [comment]
Thanks for getting this started, @lisac-usds ! Looking at this i'm realizing that now we've made 'resources' into a mish-mash of USDS-specific things and not-USDS things...and it's a little hard to tell which are going to tell me more about USDS and which are tangential resources.

As a way to solve that (plus, balance out the column length), I propose:
- rename 'get in touch' to something like 'more about USDS' 
- move d&i report, impact report, hiring faq to that 'more' column

I'll try (!) making those changes in the html file later this afternoon. CC @drew-usds and @bernars-usa since one of them will probably have good input on this.

**Comment by lisac-usds** [comment]
thanks, @LauraUSDS . 

More generally, there's some inconsistencies in the styling/logos btwn usds.gov and the discovery sprint guide - let's hold off on introducing a link to the discovery sprint guide until that's resolved.

**Comment by LauraUSDS** [comment]
@lisac-usds I see you updated the logo for the discovery sprint guide footer - THANK YOU! It looks great. As a favor in return, I updated the footer links per my suggestion above (different column name + separating links by type). Could you confirm I didn't break the HTML?

If all looks good, we can push live. _There is a world where there are probably other 'resources' links we could add (e.g., plainlanguage.gov), but let's not overcomplicate this, eh?_

**Comment by LauraUSDS** [comment]
@lisac-usds @drew-usds can one of you confirm this looks alright? i don't see the deploy preview (since we're pushing straight to master?). would love to have this live for the public announcement on monday :)

**Comment by drew-usds** [comment]
@LauraUSDS I swapped the order of the two columns of links so USDS stuff comes first. Also added `target="_blank"` to the external links so they open in a new tab. Let me know if the swapped order of cols is OK and I can _do it live_.

Screen Shot 2021-02-19 at 6 49 29 PM

**Review by drew-usds — APPROVED** [review]

**Pull request merged**
