### PR TITLE
Basic print style sheet

### PR DESCRIPTION
**Pull request by stefanwild**
Added a rudimentary print style sheet that hides (top, sidebar and footer) navigation and adjusts some spacing. Just grabbing the lowest-hanging fruit to improve printing, actually mostly just for the Join Us page. Please consider it a starting point more than anything else.

### CODE REVIEW

**Comment by charwo** [comment]
@jaredcunha can you please review?

@stefanwild thanks for the contribution!

**Comment by jaredcunha-usds** [comment]
👀

**Comment by jaredcunha-usds** [comment]
@charwo Added a few items to this in a new branch/pr. Can close this and use #294.

**Comment by charwo** [comment]
merged, thanks again @stefanwild! :us: :us: :us:

**Pull request merged**
