### PR TITLE
Update how_we_work.yml

### PR DESCRIPTION
**Pull request by clarebayley-gov**
Changing to the actual meaning of StratOps

### CODE REVIEW

**Comment by jaredcunha-usds** [comment]
@clarebayley-gov any issues with changing the ampersand to and?  Either that remove the oxford comma and keep the ampersand?

**Comment by clarebayley-gov** [comment]
I'm a fan of the oxford comma, but I also want to make sure we match the other titles and "Design & User Experience" has an ampersand. I will defer to @LauraUSDS for whatever she deems appropriate

**Comment by jaredcunha-usds** [comment]
I'm a fan of Oxford commas as well, but I think it might be strange when combined with an ampersand. Hope this helps: 
https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Punctuation/faq0081.html

@LauraUSDS - Care to weigh in?

**Comment by LauraUSDS** [comment]
Hmm. We don't currently have a default writing style (Chicago vs AP), but we're working on that! According to the internet, commas in front of ampersands is a no-no, but it's a bit confusing in this context. For consistency's sake, let's do:

>Design and User Experience

> Product, Strategy, and Operations

I also take issue with Title Case (over Sentence case) for headers, but we're not fighting that battle today. Thanks, team! @clarebayley-gov @jaredcunha

**Comment by jaredcunha-usds** [comment]
I can make the heading updates across the board on this page, @clarebayley-gov, if you don't mind that I push a commit to this.

**Comment by clarebayley-gov** [comment]
Not at all, be my guest!

**Pull request merged**
