### PR TITLE
Changed QPP website and image to most recent.

### PR DESCRIPTION
**Pull request by ghost**
Changed QPP website link to correct one.
Changed QPP website thumbnail with new screenshot.

### CODE REVIEW

**Comment by cew821** [comment]
@froi-usds this PNG file is 2.7MB. Can you compress it to something more reasonable? cc @alex cause he does this a lot.

**Comment by alex** [comment]
You can losslessly compress it with the `compresspng.sh` script in the root of the repo, but I suspect what you really want to do is use a lower resolution screenshot. This one is >2000x1000, but I think the place it's used in the website is only a few hundred pixels wide, is that right?

**Comment by ghost** [comment]
@alex Yes it is. I'll lower the resolution and resubmit. I'll also use `compresspng.sh` to make sure it's a suitable size.

**Comment by ghost** [comment]
@cew821, @alex Compressed and lowered resolution. Please let me know if this is acceptable. Thanks.

**Comment by alex** [comment]
LGTM! I'll let someone who's more involved with the website review and merge!

**Pull request merged**
